services:

  db:
    image: postgres:9.6.12
    container_name: spring3.0_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  adminer:
    image: adminer
    ports:
      - "8888:8080"